In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [4]:
print (arr)

[1 2 3 4 5 6]


In [7]:
a = [1,2,3,4,5,6]
a

[1, 2, 3, 4, 5, 6]

In [8]:
b = [1,2,3,4,5,"Heloo"]
b

[1, 2, 3, 4, 5, 'Heloo']

In [9]:
np.array(b)

array(['1', '2', '3', '4', '5', 'Heloo'], dtype='<U21')

In [10]:
l= [ [1,2,3] , [4,5,6] , [7,8,9] ]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr = np.arange(1, 11, 2)
print(arr)

[1 3 5 7 9]


In [18]:
arr = np.zeros(6)
print(arr)

[0. 0. 0. 0. 0. 0.]


In [19]:
arr = np.zeros([6,6])
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [20]:
arr = np.ones(6)
print(arr) 

[1. 1. 1. 1. 1. 1.]


In [22]:
arr = np.ones([7,4])
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
arr = np.linspace(1, 10, 5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [26]:
arr = np.random.rand(10)
print(arr)

[0.67190956 0.59402201 0.96473187 0.84833489 0.55438716 0.87565843
 0.90508932 0.58145922 0.00284122 0.71265551]


In [27]:
arr = np.random.rand(5)
print(arr)

[0.94908553 0.62900872 0.68376668 0.81490087 0.02773667]


In [28]:
arr = np.random.randn(5)
print(arr)

[ 1.02460755  0.29459864  1.11685742 -2.23905708 -0.40807789]


In [29]:
arr = np.random.randint(1, 10, 5)
print(arr)

[2 9 5 4 2]


In [30]:
np.random.randint(1, 100, (2, 3))

array([[83, 51, 60],
       [46, 47, 42]], dtype=int32)

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.shape)

(6,)


In [32]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)

(2, 3)


In [33]:
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr.shape)

(2, 2, 2)


In [34]:
print(arr.shape)   # Shape
print(arr.ndim)    # Number of dimensions
print(arr.size)    # Total elements
print(arr.dtype)   # Data type

(2, 2, 2)
3
8
int64


In [35]:
arr = np.array([10, 20, 30, 40, 50])

print(arr.max())
print(arr.min())
print(arr.sum())

50
10
150


In [36]:
arr = np.array([10, 20, 30, 40, 50])

print("Maximum :", arr.max())
print("Minimum :", arr.min())
print("Sum :", arr.sum())
print("Mean :", arr.mean())
print("Median :", np.median(arr))
print("Standard Deviation :", arr.std())
print("Variance :", arr.var())
print("Product :", arr.prod())
print("Argmax :", arr.argmax())
print("Argmin :", arr.argmin())
print("Cumulative Sum :", arr.cumsum())
print("Cumulative Product :", arr.cumprod())

Maximum : 50
Minimum : 10
Sum : 150
Mean : 30.0
Median : 30.0
Standard Deviation : 14.142135623730951
Variance : 200.0
Product : 12000000
Argmax : 4
Argmin : 0
Cumulative Sum : [ 10  30  60 100 150]
Cumulative Product : [      10      200     6000   240000 12000000]


In [38]:
# indexing 
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[0])    # 10
print(arr[2])    # 30
print(arr[5])    # 60
print(arr[-1])   # 60
print(arr[-2])   # 50

10
30
60
60
50


In [39]:
# Slicing 
print(arr[1:4])

[20 30 40]


In [40]:
print(arr[:4])

[10 20 30 40]


In [41]:
print(arr[2:])

[30 40 50 60]


In [42]:
print(arr[:])

[10 20 30 40 50 60]


In [43]:
print(arr[::-1])

[60 50 40 30 20 10]


In [45]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
# indexing
print(arr[0])

[1 2 3]


In [46]:
print(arr[:2])

[[1 2 3]
 [4 5 6]]


In [49]:
arr = np.arange(30)
arr = arr.reshape(6, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [50]:
arr[0,0]

np.int64(0)

In [51]:
arr[0:2,1:3]

array([[1, 2],
       [6, 7]])

In [57]:
arr[3:, 3:]

array([[18, 19],
       [23, 24],
       [28, 29]])

In [58]:
arr = np.array([10, 20, 30, 40, 50])

print(arr > 25)

[False False  True  True  True]
