In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4,5,6,7,8,9])
a2 = np.array([1,2,2,4,5,6,8,98,9])

print(a1)
print(a2)

[1 2 3 4 5 6 7 8 9]
[ 1  2  2  4  5  6  8 98  9]


In [3]:
a1+a2

array([  2,   4,   5,   8,  10,  12,  15, 106,  18])

In [4]:
a1*a2

array([  1,   4,   6,  16,  25,  36,  56, 784,  81])

In [5]:
a1-a2

array([  0,   0,   1,   0,   0,   0,  -1, -90,   0])

In [6]:
a1/a2

array([1.        , 1.        , 1.5       , 1.        , 1.        ,
       1.        , 0.875     , 0.08163265, 1.        ])

In [8]:
a1%a2

array([0, 0, 1, 0, 0, 0, 7, 8, 0])

In [9]:
a1//a2

array([1, 1, 1, 1, 1, 1, 0, 0, 1])

In [11]:
l = [10, 20, 30, 40, 50]
arr = np.array(l)

print(arr)

[10 20 30 40 50]


In [13]:
arr2 = np.arange(1, 26).reshape(5, 5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [14]:
# Broadcasting ka matlab hai ki NumPy different shapes wale arrays par bhi arithmetic operations kar deta hai, agar broadcasting rules follow hote hain.
arr = np.array([1,2,3,4,5])

print(arr + 10)

[11 12 13 14 15]


In [15]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print(a + b)

[11 22 33]


In [17]:
arr = np.arange(1,10).reshape(3,3)

print(arr + 5)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [18]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([10,20,30])

print(a + b)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [19]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[10],
              [20],
              [30]])

print(a + b)

[[11 12 13]
 [24 25 26]
 [37 38 39]]


In [20]:
# Deep copy
row = np.array([[1,2,3]])
col = np.array([[10],
                [20],
                [30]])

print(row + col)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [21]:
# shallow copy
a = np.array([10,20,30])

b = a.view()

b[1] = 200

print(a)
print(b)

[ 10 200  30]
[ 10 200  30]
